"""add risk_level and confidence to urlSubmissions

Revision ID: 3bee01cc4dd8
Revises: e2c25d6e8904
Create Date: 2026-05-10 11:26:12.125401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bee01cc4dd8'
down_revision = 'e2c25d6e8904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urlSubmissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urlSubmissions', schema=None) as batch_op:
        batch_op.drop_column('confidence')
        batch_op.drop_column('risk_level')

    # ### end Alembic commands ###
