"""add submission_id to explanations

Revision ID: ecd81d8c0e9b
Revises: 3bee01cc4dd8
Create Date: 2026-05-13 19:01:11.732862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd81d8c0e9b'
down_revision = '3bee01cc4dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_id', sa.Integer(), nullable=True))
        batch_op.alter_column('predictionID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_explanations_submission_id'), ['submission_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_explanations_submission_id',
            'urlSubmissions', ['submission_id'], ['submissionID'],
            ondelete='CASCADE',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_explanations_submission_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_explanations_submission_id'))
        batch_op.alter_column('predictionID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('submission_id')

    # ### end Alembic commands ###
